"""Add meta-field for ingredients

Revision ID: 296ee2115261
Revises: 8ecf8db681dd
Create Date: 2025-06-15 20:40:51.437213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296ee2115261'
down_revision = '8ecf8db681dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('meta')

    # ### end Alembic commands ###
