"""Add Image-URL to Recipe-Details

Revision ID: 699d41800674
Revises: de2de701582c
Create Date: 2025-05-09 16:34:38.905157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699d41800674'
down_revision = 'de2de701582c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
