"""Removed Ingredient-ID and made name primaryKey (nameConflicts with different IDs)

Revision ID: 890b3c27a92a
Revises: 296ee2115261
Create Date: 2025-06-15 22:17:00.048110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890b3c27a92a'
down_revision = '296ee2115261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
