"""Added saved recipes and mealplan; Add ingredients

Revision ID: 8ecf8db681dd
Revises: 9f4f7671a5aa
Create Date: 2025-06-15 19:19:42.614626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ecf8db681dd'
down_revision = '9f4f7671a5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('meal_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('input_date', sa.DateTime(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mealplan_recipe',
    sa.Column('mealplan_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mealplan_id'], ['meal_plan.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('mealplan_id', 'recipe_id')
    )
    op.create_table('user_mealplan',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mealplan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mealplan_id'], ['meal_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'mealplan_id')
    )
    op.create_table('user_saved_recipe',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_saved_recipe')
    op.drop_table('user_mealplan')
    op.drop_table('mealplan_recipe')
    op.drop_table('meal_plan')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
