"""Add sourceName and sourceUrl

Revision ID: 9f4f7671a5aa
Revises: 699d41800674
Create Date: 2025-05-19 15:36:26.563634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4f7671a5aa'
down_revision = '699d41800674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('source_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('source_url')
        batch_op.drop_column('source_name')

    # ### end Alembic commands ###
